name: flutter_car_installmemt_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0 "

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/showroom.png
    - assets/images/car.png
    - assets/icons/
